### PR TITLE
Few issues done

### PR DESCRIPTION
**Pull request by dulakm**
Hi, I've tried to fulfill some of users' requests.
Please take a look if it is OK.
Thanks!

### CODE REVIEW

**Comment by frosas** [comment]
Looks great! But please give me a few days to review it properly, you made a lot of changes :)

**Comment by m93a** [comment]
cool :)

**Comment by frosas** [comment]
Hi all, notice I closed this PR as I merged the changes locally. Thanks a lot @dulakm for such a great job!

**Comment by frosas** [comment]
Closes #43

**Pull request closed without merging**
